package com.example.balut.ui.theme

import androidx.compose.ui.graphics.Color

// Egg & Yolk Palette (Yellow/Orange Vibrant)

// Light Color Scheme
val LightPrimary = Color(0xFF805600)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFFFDDAE)
val LightOnPrimaryContainer = Color(0xFF281800)
val LightSecondary = Color(0xFF705B40)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFFBDDA0)
val LightOnSecondaryContainer = Color(0xFF251A04)
val LightTertiary = Color(0xFF526447)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFD5EABD)
val LightOnTertiaryContainer = Color(0xFF101F09)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnErrorContainer = Color(0xFF410002)
val LightBackground = Color(0xFFFFF8F1)
val LightOnBackground = Color(0xFF1F1B16)
val LightSurface = Color(0xFFFFF8F1)
val LightOnSurface = Color(0xFF1F1B16)
val LightSurfaceVariant = Color(0xFFF0E0CB)
val LightOnSurfaceVariant = Color(0xFF4F4535)
val LightOutline = Color(0xFF817564)

// Dark Color Scheme
val DarkPrimary = Color(0xFFFFBA3F)
val DarkOnPrimary = Color(0xFF442B00)
val DarkPrimaryContainer = Color(0xFF614000)
val DarkOnPrimaryContainer = Color(0xFFFFDDAE)
val DarkSecondary = Color(0xFFDDBF9B)
val DarkOnSecondary = Color(0xFF3E2D16)
val DarkSecondaryContainer = Color(0xFF56432A)
val DarkOnSecondaryContainer = Color(0xFFFBDDA0)
val DarkTertiary = Color(0xFFB9CEA3)
val DarkOnTertiary = Color(0xFF253519)
val DarkTertiaryContainer = Color(0xFF3B4C2F)
val DarkOnTertiaryContainer = Color(0xFFD5EABD)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFDAD6)
val DarkBackground = Color(0xFF1F1B16)
val DarkOnBackground = Color(0xFFEAE1D9)
val DarkSurface = Color(0xFF1F1B16)
val DarkOnSurface = Color(0xFFEAE1D9)
val DarkSurfaceVariant = Color(0xFF4F4535)
val DarkOnSurfaceVariant = Color(0xFFD2C4B1)
val DarkOutline = Color(0xFF9B8F7D)
